# Rustfmt configuration to reduce formatting warnings
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"
indent_style = "Block"
wrap_comments = false
format_code_in_doc_comments = false
comment_width = 80
normalize_comments = false
license_template_path = ""
format_strings = false
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
short_array_element_width_threshold = 10
struct_field_align_threshold = 0
struct_lit_width_threshold = 18
struct_variant_width_threshold = 0
match_arm_leading_pipes = "Never"
match_arm_blocks = false
match_block_trailing_comma = false
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
trailing_semicolon = true
trailing_comma = "Vertical"
space_before_colon = false
space_after_colon = true
spaces_around_ranges = false
binop_separator = "Front"
remove_empty_lines_between_match_arms = true
blank_lines_before_fn_single_line = false
proc_macro_trailing_semicolon = false
wrap_multiple_type_params_in_parens = false
space_before_type_annotation = false
space_before_struct_lit_field_colon = false
struct_lit_single_line = false
fn_single_line = false
where_single_line = false
imports_indent = "Block"
imports_layout = "Mixed"
merge_imports = false
normalize_doc_attributes = false
format_macro_matchers = false
format_macro_bodies = true
hex_literal_case = "Lower"
use_field_init_shorthand = false
force_explicit_abi = true
condense_wildcard_suffixes = false
color = "Auto"
required_version = "1.4.38"
unstable_features = false
disable_all_formatting = false
skip_children = false
hide_parse_errors = false
error_on_line_overflow = false
error_on_unformatted = false
report_todo = "Never"
report_fixme = "Never"
ignore = []