ai_enabled = false
fuzzy_distance = 2
max_search_results = 1000
watch_enabled = false
watch_clear_screen = false
output_format = "Text"
pretty_json = false
show_line_numbers = true
ai_timeout_seconds = 30
ai_memory_limit_mb = 1024
spelling_enabled = true
spelling_max_distance = 2
spelling_min_score = 0.8
language_detection_enabled = true
index_dir = ".ricegrep"
max_file_size_mb = 10
mcp_enabled = false
plugin_dirs = [".ricegrep/plugins"]
plugin_enabled = []
store_enabled = true
store_path = ".ricegrep/store"
